### ISSUE TITLE
Cannot get account from appwrite

### ISSUE THREAD

**Issue by ludwing979** [adrianhajdin/social_media_app#7] opened 2023-11-02 16:28 UTC
When the code in the file config.ts executes this line 
` const currentAccount = await account.get()`
it does not connect to Appwrite, in the console shows this:

<img width="304" alt="image" src="https://github.com/adrianhajdin/social_media_app/assets/31998765/9c0c9592-5d1b-4758-8f0a-6111e804de6b">

Does anyone have the same issue?

**Comment by yang2674** [comment] 2023-11-03 00:18
Yes, I ran into this issue.

I solved it by starting a "web" client, and changing permissions to `*`
![Screenshot 2023-11-02 191737](https://github.com/adrianhajdin/social_media_app/assets/94493230/98fa722d-4045-48be-bec5-c6137401d195)

**Comment by ludwing979** [comment] 2023-11-03 19:30
I tried that but still is not working, I also tried to delete the project and create a new one but still is getting the same error

**Comment by yang2674** [comment] 2023-11-04 20:27
> I tried that but still is not working, I also tried to delete the project and create a new one but still is giving me the same error

If your code is 100% correct, it has to be appwrite.

Make sure you set up your auth and database correctly. That's the best advice I can give without looking at your code.

**Comment by Aashish1009** [comment] 2023-11-09 02:53
im also getting same issue

**Comment by Proj-Valentine** [comment] 2023-11-09 06:48
I am getting the same issue too, cant connect with appwrite

**Comment by Proj-Valentine** [comment] 2023-11-09 18:56
> Yes, I ran into this issue.
> 
> I solved it by starting a (1) "web" client, and (2) changing hostname to `*`
> 
> ![Screenshot 2023-11-02 191737](https://user-images.githubusercontent.com/94493230/280158150-98fa722d-4045-48be-bec5-c6137401d195.png)

Can step by step run through what you did for it to work?

**Comment by yang2674** [comment] 2023-11-09 19:00
> I tried that but still is not working, I also tried to delete the project and create a new one but still is giving me the same error

https://github.com/adrianhajdin/social_media_app/issues/3#issuecomment-1804029493

**Comment by yang2674** [comment] 2023-11-09 19:01
Sorry I haven't had time to write a proper response, but @Rondev9 created it here. These are the steps you must take: https://github.com/adrianhajdin/social_media_app/issues/3#issuecomment-1804029493

**Comment by yang2674** [comment] 2023-11-09 19:02
> I tried that but still is not working, I also tried to delete the project and create a new one but still is giving me the same error

Sorry I haven't had time to write a proper response, but @Rondev9 created it here. These are the steps you must take: https://github.com/adrianhajdin/social_media_app/issues/3#issuecomment-1804029493

**Comment by athskouroliakos** [comment] 2023-11-15 12:48
I am dealing with the same issue and creating a web platform did not fix it.

**Comment by ludwing979** [comment] 2023-11-15 19:25
> > When the code in the file config.ts executes this line ` const currentAccount = await account.get()` it does not connect to Appwrite, in the console shows this:
> > <img alt="image" width="304" src="https://user-images.githubusercontent.com/31998765/280061025-9c0c9592-5d1b-4758-8f0a-6111e804de6b.png">
> > Does anyone have the same issue?
> 
> did you get the issue resolved?

No, I search for different solutions but I still can't figure it out

**Comment by athskouroliakos** [comment] 2023-11-16 11:59
> > > > When the code in the file config.ts executes this line ` const currentAccount = await account.get()` it does not connect to Appwrite, in the console shows this:
> > > > <img alt="image" width="304" src="https://user-images.githubusercontent.com/31998765/280061025-9c0c9592-5d1b-4758-8f0a-6111e804de6b.png">
> > > > Does anyone have the same issue?
> > > 
> > > 
> > > did you get the issue resolved?
> > 
> > 
> > No, I search for different solutions but I still can't figure it out
> 
> Hey @ludwing979 in order to tackle with the 401, I'm using local storage to store the userId (as a bruteforce method) and on sign out I'm clearing the local storage to delete the current user session. Here's the reference:
> 
> **Sign-in:**
> 
> ```
> export async function signInAccount(user: { email: string; password: string }) {
>   try {
>     const session = await account.createEmailSession(user.email, user.password);
>     localStorage.setItem("sessionId", session.userId); //userId stored as a sessionId -> purpose of storing is after some time of user log in, when try to fetch useId on reload the appWrite is unable to fetch resulting 401
>     return session;
>   } catch (error) {
>     console.log(error);
>   }
> }
> ```
> 
> **Sign-out:**
> 
> ```
> export async function signOutAccount() {
>   try {
>     localStorage.clear();
>     const session = await account.deleteSession("current");
>     return session;
>   } catch (error) {
>     console.log(error);
>   }
> }
> ```
> 
> Hope it helps 😊

I tried that but the issue remains, the problem as shown in the screenshot seems to be at the getCurrentUser.

![apprwrite_401](https://github.com/adrianhajdin/social_media_app/assets/79373169/b6d2ec81-5dfe-4c35-ba5d-393a028f8197)

**Comment by Rondev9** [comment] 2023-11-16 16:17
Hey @athskouroliakos, If it's acceptable to you, kindly add me to your repository. This will allow me to thoroughly study the code, and I assure you that I will contribute towards resolving the error.

**Comment by ludwing979** [comment] 2023-11-16 17:00
@Rondev9 Can I also add you to my repository to check, I have the same problem as @athskouroliakos

**Comment by Rondev9** [comment] 2023-11-16 17:08
> @Rondev9 Can I also add you to my repository to check, I have the same problem as @athskouroliakos 

Sure @ludwing979! Please go ahead.

**Comment by TheerthA88** [comment] 2023-11-20 14:24
> > > When the code in the file config.ts executes this line ` const currentAccount = await account.get()` it does not connect to Appwrite, in the console shows this:
> > > <img alt="image" width="304" src="https://user-images.githubusercontent.com/31998765/280061025-9c0c9592-5d1b-4758-8f0a-6111e804de6b.png">
> > > Does anyone have the same issue?
> > 
> > 
> > did you get the issue resolved?
> 
> No, I search for different solutions but I still can't figure it out

Is it fixed?

**Comment by IasmimCristina** [comment] 2023-11-24 19:18
Were you able to fix it? @athskouroliakos @Rondev9 , I'm facing the same issue.

**Comment by TheerthA88** [comment] 2023-11-24 20:03
> Were you able to fix it? @athskouroliakos @Rondev9 , I'm facing the same issue.

@IasmimCristina, can you pls share the screenshots if you don't mind

**Comment by IasmimCristina** [comment] 2023-11-24 20:37
Here they are:
Im basically receiving the same error as the author of the issue, I've already added the Web platform, and re-made the project in appwrite and checked JSM's code. Weirdly, yesterday it was working fine, but now when I re-load the page the session doesnt work.

![Captura de tela de 2023-11-24 17-25-17](https://github.com/adrianhajdin/social_media_app/assets/100351576/d12c2a4c-351d-430f-aea4-cf2a8ea053b4)
The local storage message appears once I login and the first ones as soon as the app loads the signin page.
![Captura de tela de 2023-11-24 17-25-36](https://github.com/adrianhajdin/social_media_app/assets/100351576/da5f761b-799e-435e-9893-ee7430fb1cd6)
Here are the functions and console ninja error messages, the same mentioned:
![Captura de tela de 2023-11-24 17-17-32](https://github.com/adrianhajdin/social_media_app/assets/100351576/56b58fc0-b4a5-444c-9261-ce4fdb424ec9)
The unathourized error is refering to this line:
`const currentAccount = await account.get();`

![Captura de tela de 2023-11-24 17-24-08](https://github.com/adrianhajdin/social_media_app/assets/100351576/6f1e7b75-939b-4e2e-a98d-0f36202e6a95)

**Comment by TheerthA88** [comment] 2023-11-24 21:15
@IasmimCristina , Can u please try replacing the 
appwriteConfig.databaseId and appwriteConfig.useCollectionId 
with the values of those in quotes

![image](https://github.com/adrianhajdin/social_media_app/assets/61548780/4b2c7568-4b9a-46ce-837a-42317f62e05a)

**Comment by IasmimCristina** [comment] 2023-11-24 22:11
> @IasmimCristina , Can u please try replacing the 
> appwriteConfig.databaseId and appwriteConfig.useCollectionId 
> with the values of those in quotes
> 
> ![image](https://github.com/adrianhajdin/social_media_app/assets/61548780/4b2c7568-4b9a-46ce-837a-42317f62e05a)
> 
> 

Hello!

I have done that, actually, my code was like that but I changed it when I made that screenshot.
(And it was with the double quotes 😢)

 The difference it makes is that when the sign in page loads it doesn't get the unauthorized error message. 

However, when I reload the page the session doesn't persist still and when I logout I get the unauthorized error message again.

**Comment by Rondev9** [comment] 2023-11-25 02:22
> > @IasmimCristina , Can u please try replacing the 
> > appwriteConfig.databaseId and appwriteConfig.useCollectionId 
> > with the values of those in quotes
> > 
> > ![image](https://github.com/adrianhajdin/social_media_app/assets/61548780/4b2c7568-4b9a-46ce-837a-42317f62e05a)
> > 
> > 
> 
> Hello!
> 
> I have done that, actually, my code was like that but I changed it when I made that screenshot.
> (And it was with the double quotes 😢)
> 
>  The difference it makes is that when the sign in page loads it doesn't get the unauthorized error message. 
> 
> However, when I reload the page the session doesn't persist still and when I logout I get the unauthorized error message again. 

Hey @IasmimCristina, If you don't mind, can you please invite me to your project repo, I'll do my best to resolve the issue.

**Comment by IasmimCristina** [comment] 2023-11-25 18:13
@Rondev9 , thank you very much, I invited you just now.

**Comment by Onunkwor** [comment] 2023-12-06 22:18
I having the 401 authorization issue when I try to sign up or sign in. The users are correctly added to app write and the local storage but the page doesn't redirect and I have these issues 

<img width="449" alt="Screenshot 2023-12-06 225449" src="https://github.com/adrianhajdin/social_media_app/assets/126721072/dff12882-7f5f-43ed-b8f8-cecb2059ef1a">

**Comment by Rondev9** [comment] 2023-12-08 04:55
"Fantastic @Onunkwor! 🎉 I'm glad to hear that you resolved the issue. It's always those little details that can make a big difference. Kudos! Also, great catch on fixing the getCurrentUser function—consistent casing is key. If you run into any more challenges or have questions in the future, feel free to reach out. Happy coding! 👩‍💻🚀"

**Comment by sridhar-pro** [comment] 2023-12-09 06:41
@Onunkwor I updated the code but still getting same error 
can you help me to fix this
![Screenshot 2023-12-09 120825](https://github.com/adrianhajdin/social_media_app/assets/148807462/4f7bd2cd-cd1a-44c3-beea-983ab6b83d65)
![Screenshot 2023-12-09 120841](https://github.com/adrianhajdin/social_media_app/assets/148807462/64729f6f-17f6-41a3-88da-3ffdae49be36)

![Screenshot 2023-12-09 121106](https://github.com/adrianhajdin/social_media_app/assets/148807462/9b74a93d-ee5a-47e1-90c3-980bc7e1b3f5)

**Comment by sridhar-pro** [comment] 2023-12-09 06:43
@Onunkwor I updated the code but still getting same error
can you help me to fix this

![Screenshot 2023-12-09 121236](https://github.com/adrianhajdin/social_media_app/assets/148807462/5b99ce48-158d-460d-bba4-5852c015890a)

![Screenshot 2023-12-09 121250](https://github.com/adrianhajdin/social_media_app/assets/148807462/7411aeb7-4380-40cd-b0cf-d09ef2307b57)


![Screenshot 2023-12-09 121305](https://github.com/adrianhajdin/social_media_app/assets/148807462/9e532be6-5982-45fa-9637-2672a08f580d)

**Comment by Onunkwor** [comment] 2023-12-10 09:01
@sridhar-pro  Good morning, Are you using .env or .env.local for your API keys?

**Comment by sridhar-pro** [comment] 2023-12-11 07:17
@Onunkwor i'am using .env local for the API keys

**Comment by Onunkwor** [comment] 2023-12-13 13:05
@sridhar-pro Sorry about the late reply; I've been caught up with schoolwork. I encountered an error where the API keys were not accessed properly when I used .env.local, so I switched to just .env, and it worked fine.

**Comment by sridhar-pro** [comment] 2023-12-15 07:28
@Onunkwor thank you brother it's worked

**Comment by Onunkwor** [comment] 2023-12-15 08:53
@sridhar-pro you're welcome

**Comment by siya-pathak** [comment] 2023-12-21 12:27
> @Rondev9 , thank you very much, I invited you just now.
hey! were you able to resolve the issue? i have been facing the same problem for a few hours now and have been unable to tackle it

**Comment by siya-pathak** [comment] 2023-12-21 13:06
> > > @Rondev9 , thank you very much, I invited you just now.
> > 
> > 
> > hey! were you able to resolve the issue? i have been facing the same problem for a few hours now and have been unable to tackle it
> 
> Hey @siya-pathak, Yeah I'm able to resolve it.

hi could you tell me how did you? i did refer to [https://github.com/adrianhajdin/social_media_app/issues/19#issuecomment-1807460381](this comment here) and the sign-up is working fine now after making this modification, but i just wanted to know any other way this could be solved :)

**Comment by Rondev9** [comment] 2023-12-21 13:14
> > > > @Rondev9 , thank you very much, I invited you just now.
> > > 
> > > 
> > > hey! were you able to resolve the issue? i have been facing the same problem for a few hours now and have been unable to tackle it
> > 
> > Hey @siya-pathak, Yeah I'm able to resolve it.
> 
> hi could you tell me how did you? i did refer to [https://github.com/adrianhajdin/social_media_app/issues/19#issuecomment-1807460381](this comment here) and the sign-up is working fine now after making this modification, but i just wanted to know any other way this could be solved :)

You can use local storage to save the user ID, so that it won't complain about the 401 as we're using the user id from local storage whenever we make a call to AppWrite. So why we're using local storage here, overtime AppWrite fails to fetch the user id from AppWrite's session, which results in 401. And don't forget to clear the local storage on sign out.

**Comment by siya-pathak** [comment] 2023-12-21 13:22
> > > > > @Rondev9 , thank you very much, I invited you just now.
> > > > 
> > > > 
> > > > hey! were you able to resolve the issue? i have been facing the same problem for a few hours now and have been unable to tackle it
> > > 
> > > 
> > > Hey @siya-pathak, Yeah I'm able to resolve it.
> > 
> > 
> > hi could you tell me how did you? i did refer to [https://github.com/[/issues/19](https://github.com/adrianhajdin/social_media_app/issues/19)#issuecomment-1807460381](this comment here) and the sign-up is working fine now after making this modification, but i just wanted to know any other way this could be solved :)
> 
> You can use local storage to save the user ID, so that it won't complain about the 401 as we're using the user id from local storage whenever we make a call to AppWrite. So why we're using local storage here, overtime AppWrite fails to fetch the user id from AppWrite's session, which results in 401. And don't forget to clear the local storage on sign out.

thank you so much for this :)

**Comment by Rondev9** [comment] 2023-12-21 13:27
> > > > > > @Rondev9 , thank you very much, I invited you just now.
> > > > > 
> > > > > 
> > > > > hey! were you able to resolve the issue? i have been facing the same problem for a few hours now and have been unable to tackle it
> > > > 
> > > > 
> > > > Hey @siya-pathak, Yeah I'm able to resolve it.
> > > 
> > > 
> > > hi could you tell me how did you? i did refer to [https://github.com/[/issues/19](https://github.com/adrianhajdin/social_media_app/issues/19)#issuecomment-1807460381](this comment here) and the sign-up is working fine now after making this modification, but i just wanted to know any other way this could be solved :)
> > 
> > You can use local storage to save the user ID, so that it won't complain about the 401 as we're using the user id from local storage whenever we make a call to AppWrite. So why we're using local storage here, overtime AppWrite fails to fetch the user id from AppWrite's session, which results in 401. And don't forget to clear the local storage on sign out.
> 
> thank you so much for this :)

You're welcome @siya-pathak. Happy coding 🚀🚀

**Comment by ToufikGouri** [comment] 2024-01-27 12:26
When i am creating a new user, even it gets stored in my DB of appwrite, then still it can't get updated in my redux  store, the login and logout is working fine only the Signup is creating problem
Please help me anybody

my userdetails slice looks like this 
export const userDetails = createAsyncThunk('userDetails', async () => {
    try {
        const getData = await account.get()
        return getData;
    } catch (error) {
        return 0
    }
})
worked fine with login and logout just problem with the Signup

Sign up function :
    e.preventDefault()

        const promise = account.create(
            uuidv4(),
            user.email,
            user.password,
            user.name
        );

        promise.then(
            function (response) {
                console.log(response);
                if (response) {
                    dispatch(userDetails()); // Dispatch userDetails action to update the Redux state
                }
                navigate("/")   //Success
            },
            function (error) {
                console.log(error);    //Failed
            }
        )

    }
    
    
    please help meeee

**Comment by rahulAgdev** [comment] 2024-02-02 14:08
I faced the same issue, it is because account.get() will not return the current account immediately, which throws the execution to the catch block. And hence you are receiving this error. 

To solve this error, I created a separate function to get the current user using the account.get function and then call it inside the getCurrentUser function ( if that is what you have named it ) 

```
export async function getAccount() {
  try {
    const currentAccount = await account.get();

    return currentAccount;
  } catch (error) {
    console.log(error);
  }
}
```

then use this getAccount function to fetch your user account details in your main function.

**Closed** 2024-02-02 16:44 UTC

**Comment by ToufikGouri** [comment] 2024-02-03 16:34
> I faced the same issue, it is because account.get() will not return the current account immediately, which throws the execution to the catch block. And hence you are receiving this error.
> 
> To solve this error, I created a separate function to get the current user using the account.get function and then call it inside the getCurrentUser function ( if that is what you have named it )
> 
> ```
> export async function getAccount() {
>   try {
>     const currentAccount = await account.get();
> 
>     return currentAccount;
>   } catch (error) {
>     console.log(error);
>   }
> }
> ```
> 
> then use this getAccount function to fetch your user account details in your main function.

But bro as you can see in my starting line of response the code is same as like yours, I used the async await to get user in seperate function :(

**Comment by rahulAgdev** [comment] 2024-02-03 16:46
> > I faced the same issue, it is because account.get() will not return the current account immediately, which throws the execution to the catch block. And hence you are receiving this error.
> > 
> > To solve this error, I created a separate function to get the current user using the account.get function and then call it inside the getCurrentUser function ( if that is what you have named it )
> > 
> > ```
> > export async function getAccount() {
> >   try {
> >     const currentAccount = await account.get();
> > 
> >     return currentAccount;
> >   } catch (error) {
> >     console.log(error);
> >   }
> > }
> > ```
> > 
> > then use this getAccount function to fetch your user account details in your main function.
> 
> But bro as you can see in my starting line of response the code is same as like yours, I used the async await to get user in seperate function :(

Can you try to call the account.create() function seperately and call it again by returning from another function and try. If this doesn't work, let's connect and debug this together

**Comment by bizrockman** [comment] 2024-04-19 19:06
I debugged it a little bit further. Actually this error makes complete sense. And it is not a bug like it was mentioned in the video.

It behaves like intended. You are not logged in so you go to sign-in. As soon as you comment out cookieFallback === null, the method checkAuthUser() is called, but since you are guest (not a logged In user) you do not have an account. So this error occurs.

How this is setup up you will never see the sign-up page.

Now change the line in useEffect to /sign-up.

After you sign-up you will automatically logged In and after you will not get that error any longer.

I did not through with the video, So I do not know how the pageflow will be. But I think that you need some expections while checking the user. If you are not logged In I would redirect you to sign-up. If you click on sign-in you need a further check in useEffect, to ensure that the user stays on sign-in without gettting redirected to sign-up again. 

And then you are done ;-)

**Comment by bizrockman** [comment] 2024-04-23 16:15
Ok, I have managed it to work correctly with an easy fix:

`const [isAuthenticated, setIsAuthenticated] = useState(false)

    const navigate = useNavigate()
    const location = useLocation()

    const checkAuthUser = async () => {
        setIsLoading(true)
        try {
`

Add const location = userLocation()

and use it in the useEffect Method

`    useEffect(() => {
        const cookieFallback = localStorage.getItem("cookieFallback");
        if (
          cookieFallback === "[]" ||
          cookieFallback === null ||
          cookieFallback === undefined
        ) {
          if (location.pathname === "/sign-in") {
            navigate("/sign-in");  
          } else {
            navigate("/sign-up"); 
          }
        } 
        
        checkAuthUser();        
      }, []);
`

Now the app is working as expected without the 401 Unauthorized User guest as not account exception

**Comment by getoutofhereman** [comment] 2024-04-28 08:16
> > > > When the code in the file config.ts executes this line ` const currentAccount = await account.get()` it does not connect to Appwrite, in the console shows this:
> > > > <img alt="image" width="304" src="https://user-images.githubusercontent.com/31998765/280061025-9c0c9592-5d1b-4758-8f0a-6111e804de6b.png">
> > > > Does anyone have the same issue?
> > > 
> > > 
> > > did you get the issue resolved?
> > 
> > 
> > No, I search for different solutions but I still can't figure it out
> 
> Hey @ludwing979 in order to tackle with the 401, I'm using local storage to store the userId (as a bruteforce method) and on sign out I'm clearing the local storage to delete the current user session. Here's the reference:
> 
> **Sign-in:**
> 
> ```
> export async function signInAccount(user: { email: string; password: string }) {
>   try {
>     const session = await account.createEmailSession(user.email, user.password);
>     localStorage.setItem("sessionId", session.userId); //userId stored as a sessionId -> purpose of storing is after some time of user log in, when try to fetch useId on reload the appWrite is unable to fetch resulting 401
>     return session;
>   } catch (error) {
>     console.log(error);
>   }
> }
> ```
> 
> **Sign-out:**
> 
> ```
> export async function signOutAccount() {
>   try {
>     localStorage.clear();
>     const session = await account.deleteSession("current");
>     return session;
>   } catch (error) {
>     console.log(error);
>   }
> }
> ```
> 
> Hope it helps 😊



> > > > When the code in the file config.ts executes this line ` const currentAccount = await account.get()` it does not connect to Appwrite, in the console shows this:
> > > > <img alt="image" width="304" src="https://user-images.githubusercontent.com/31998765/280061025-9c0c9592-5d1b-4758-8f0a-6111e804de6b.png">
> > > > Does anyone have the same issue?
> > > 
> > > 
> > > did you get the issue resolved?
> > 
> > 
> > No, I search for different solutions but I still can't figure it out
> 
> Hey @ludwing979 in order to tackle with the 401, I'm using local storage to store the userId (as a bruteforce method) and on sign out I'm clearing the local storage to delete the current user session. Here's the reference:
> 
> **Sign-in:**
> 
> ```
> export async function signInAccount(user: { email: string; password: string }) {
>   try {
>     const session = await account.createEmailSession(user.email, user.password);
>     localStorage.setItem("sessionId", session.userId); //userId stored as a sessionId -> purpose of storing is after some time of user log in, when try to fetch useId on reload the appWrite is unable to fetch resulting 401
>     return session;
>   } catch (error) {
>     console.log(error);
>   }
> }
> ```
> 
> **Sign-out:**
> 
> ```
> export async function signOutAccount() {
>   try {
>     localStorage.clear();
>     const session = await account.deleteSession("current");
>     return session;
>   } catch (error) {
>     console.log(error);
>   }
> }
> ```
> 
> Hope it helps 😊


Bro can you please help me solve this issue in javascript
Failed to load resource: the server responded with a status of 401( )
Image of error
![github](https://github.com/adrianhajdin/social_media_app/assets/150436428/42a14564-9ac3-447b-8e45-eff1452b2af6)

**Comment by captaincharan** [comment] 2024-05-13 11:24
@Rondev9 Please help me I am struggling with he issue
